Adding 2D StartKit
MonoGame/MonoGame.Templates pull request #3
Opened 2024-12-04 17:38 UTC by CartBlanche

2024-12-07 13:37 UTC, CartBlanche commented
@mrhelmut , @dellis1972, @SimonDarksideJ: I think the StartKit is now feature complete. 
Next steps are:
- [ ] Have a 2D Pro look through the code and point out what needs to change for "best practices"
- [ ] Comment (allmost) ALL the things
- [ ] Fix input scaling bug (may need another pair of eyes on this)

2024-12-08 15:19 UTC, SimonDarksideJ commented
Best check the image links in the ReadMe @CartBlanche :D

2024-12-08 15:23 UTC, SimonDarksideJ commented
I don't have access to review @CartBlanche , must be permissions?

Main query at this point, is that the "Blank" multi-platform project should be just that, blank.

* 2D Starter kit - a basic 2D multi-platform project
* Blank multi-platform kit - A blank project with just a bare bones game1.cs like the other blank projects.


Unless you also want a 2D start kit with framework as well?  Which tbh, is a bit overkill.

2024-12-11 11:14 UTC, SimonDarksideJ commented
I thought we agreed to use a non proprietary font @CartBlanche , but the SpriteFonts are set to use Arial ?

2024-12-11 17:49 UTC, CartBlanche commented
@SimonDarksideJ Font is placeholder until we decide which font to ship in all of our samples and templates.

Blank has now been trimmed down even further. So no menu items or menus.

2024-12-17 17:50 UTC, CartBlanche commented
> Best check the image links in the ReadMe @CartBlanche :D

@SimonDarksideJ the links to the images work, when you click on the them, but can't get them to appear in the PR itself.

2025-03-11 17:02 UTC, SimonDarksideJ requested changes
Concerns over an accelerometer class that does not get accelerometer data and a blank template that is not "blank"?

2025-03-11 17:02 UTC, SimonDarksideJ commented on CSharp/content/MonoGame.2D.StartKit.CSharp/___SafeGameName___.Core/Inputs/Accelerometer.cs
> +    public static AccelerometerState GetState()
I'm confused, why is this here when "GetState" only returns a new Vector3 and does not return any actual Accelerometer data?

Isn't this just going to confuse people?

2025-03-11 17:02 UTC, SimonDarksideJ commented on CSharp/content/MonoGame.Blank.2D.StartKit.CSharp/___SafeGameName___.Core/Effects/Particle.cs
> +namespace ___SafeGameName___.Core.Effects;
For a blank starter kit, there still appears to be a log of "content" here?

Shouldn't the blank starter kit be blank, apart from a new Content Project and Basic game1.cs?  I thought the aim was for a multi-platform blank template.

2025-03-14 10:50 UTC, CartBlanche commented on CSharp/content/MonoGame.2D.StartKit.CSharp/___SafeGameName___.Core/Inputs/Accelerometer.cs
> +    public static AccelerometerState GetState()
@SimonDarksideJ I'll look into this today.

2025-03-14 10:52 UTC, CartBlanche commented on CSharp/content/MonoGame.Blank.2D.StartKit.CSharp/___SafeGameName___.Core/Effects/Particle.cs
> +namespace ___SafeGameName___.Core.Effects;
@SimonDarksideJ All effects etc have now been removed. Only thing left in, which I think devs need to address on game creation is having Localisation built in at the start.

2025-03-14 11:26 UTC, CartBlanche commented on CSharp/content/MonoGame.2D.StartKit.CSharp/___SafeGameName___.Core/Inputs/Accelerometer.cs
> +    public static AccelerometerState GetState()
@SimonDarksideJ Incidentally Windows Phone used to have a Microsoft.Devices.Sensors namespace, but seems there was never a XNA.Devices.Sensors; Maybe something worth adding down the line? I think I stripped out the WinPhone stuff from this class, and that's why it's look the way it does. Trying to fix it now.

2025-03-14 14:24 UTC, SimonDarksideJ commented on CSharp/content/MonoGame.2D.StartKit.CSharp/___SafeGameName___.Core/Inputs/Accelerometer.cs
> +    public static AccelerometerState GetState()
Yeah, XNA never did have a Sensors class, all they did was highlight/enable the Windows CE/mobile Microsoft.Devices.Sensors class and provided it in XNA on those devices.
XNA wasn't truly built to be cross-platform, just the same exe runnable on Windows and Xbox, Phone changed that, but all they did was use what the platform gave and stubbed the libraries out for Windows/Xbox so they didn't throw errors.

2025-03-14 14:25 UTC, SimonDarksideJ commented on CSharp/content/MonoGame.2D.StartKit.CSharp/___SafeGameName___.Core/Inputs/Accelerometer.cs
> +    public static AccelerometerState GetState()
Unless there is corresponding sensor data for iOS and Android, we can probably drop this.

2025-03-14 18:45 UTC, CartBlanche commented on CSharp/content/MonoGame.2D.StartKit.CSharp/___SafeGameName___.Core/Inputs/Accelerometer.cs
> +    public static AccelerometerState GetState()
Well there are definitely native sensor classes we can hook into.

2025-03-17 14:20 UTC, CartBlanche commented on CSharp/content/MonoGame.2D.StartKit.CSharp/___SafeGameName___.Core/Inputs/Accelerometer.cs
> +    public static AccelerometerState GetState()
@SimonDarksideJ Looks like we have Accelerometer classes, but they weren't being surfaced. I've just created a PR, which should then mean in the next release they'll be available so we can use them in a more cross-platform way. PR is here - https://github.com/MonoGame/MonoGame/pull/8663

Since we don't readily have these available, I'll remove the Accelerometer code for now and re-implement it (hopefully 5 min job) in a future release of the 2D StartKit.

2025-04-04 14:58 UTC, SimonDarksideJ approved these changes

2025-04-04 15:11 UTC, merged